[base]
name = "topos-node-1"
role = "validator"
subnet = "topos"

[edge]
libp2p="0.0.0.0:1478"
jsonrpc="0.0.0.0:8545"
prometheus="0.0.0.0:5001"
price-limit="0"

[tce]
db-path = "tce_rocksdb"
graphql-api-addr = "0.0.0.0:4030"
grpc-api-addr = "0.0.0.0:1340"
metrics-api-addr = "0.0.0.0:3030"
minimum-tce-cluster-size = 3

[tce.p2p]
listen-addresses = ["/ip4/0.0.0.0/tcp/9090"]
public-addresses = ["/dns4/topos-node-1/tcp/9090"]
